{
  try {
    task.run();
  }
 catch (  Throwable e) {
    exceptionCallback.onException(e);
  }
}
